### ISSUE TITLE
Potential performance enhancements?

### ISSUE THREAD

**Issue by cswkim** [brianmtully/flutter_google_ml_vision#10]
First and foremost, thank you so much for this package. I had no issues setting this up and it seems to be working as intended. This may be out of scope for the library but I wanted to explore any potential areas for performance gains. I'm testing on an older physical device (iPhone 6S from 2015) and it runs fairly smooth using the `100ms` delay between detection calls and I even upped the resolution to `high`. On a 60fps device I guess the `100ms` delay equates to roughly detecting every 6 frames? What are everyone else's experience regarding frame rendering, battery life, memory, CPU, etc.? Using DevTools performance profiler the raster UI and UI thread times are steady and on average well below the threshold for jank, so all good there.

I came across this older flutter [issue](https://github.com/flutter/flutter/issues/48360#issuecomment-572007080) discussing image processing in isolates and garbage collection and wondered if it applied at all to this package? Are isolates in general something that could be used for performance gains?

**Comment by brianmtully** [comment]
Hi, I will look at that flutter issue and get back to you. I haven't had much issues with performance but any gains would be great.

**Comment by brianmtully** [comment]
Hi Chris,

This possible performance enhancement would be outside of the scope of this package. You will find a concatenatePlanes function in the example project though. You could try the suggested function as a replacement for the one in the example project and see if that improves performance.
