### ISSUE TITLE
Why ALL_POINTS face contour isn't included?

### ISSUE THREAD

**Issue by shliama** [brianmtully/flutter_google_ml_vision#11]
https://github.com/brianmtully/flutter_google_ml_vision/blob/a6ab314fe549696e16af6591aab8056b867ff7e6/android/src/main/java/com/brianmtully/flutter/plugins/googlemlvision/GMLKFaceDetector.java#L109

Man I had to debug it for hour until decided to go check the source code (my bad). Any reason to not include the ALL_POINTS face contour?

**Comment by shliama** [comment]
Worth mentioning, in iOS version it is included - but it uses MLKFaceContourTypeFace key (Face oval) to extract data, which is wrong. It has only 36 points instead of full 133 points contour.

https://github.com/brianmtully/flutter_google_ml_vision/blob/a6ab314fe549696e16af6591aab8056b867ff7e6/ios/Classes/FaceDetector.m#L78

**Comment by brianmtully** [comment]
I have published a new version of the plugin with the ALL_POINTS face contour included now, also fixed on iOS.

**Comment by shliama** [comment]
Wow, that was fast! Thanks, it works fine now 🙌
