### ISSUE TITLE
Conflicting with new firebase packages "CocoaPods could not find compatible versions for pod "GoogleDataTransport"

### ISSUE THREAD

**Issue by usestrive** [brianmtully/flutter_google_ml_vision#12]

**Comment by brianmtully** [comment]
You might want to try what's described here:

https://stackoverflow.com/questions/62423247/cocoapods-could-not-find-compatible-versions-for-pod-googledatatransport-when-in

**Comment by bananagag** [comment]
@brianmtully The problem remains even I followed the instruction on that thread. Please reopen the issue.

[!] CocoaPods could not find compatible versions for pod "GoogleDataTransport":
  In Podfile:
    firebase_crashlytics (from `.symlinks/plugins/firebase_crashlytics/ios`) was resolved to 2.0.4, which depends on
      Firebase/Crashlytics (= 8.0.0) was resolved to 8.0.0, which depends on
        FirebaseCrashlytics (`~`> 8.0.0) was resolved to 8.0.0, which depends on
          GoogleDataTransport (~> 9.0)

    google_ml_vision (from `.symlinks/plugins/google_ml_vision/ios`) was resolved to 0.0.2, which depends on
      GoogleMLKit/FaceDetection was resolved to 0.60.0, which depends on
        GoogleMLKit/MLKitCore (= 0.60.0) was resolved to 0.60.0, which depends on
          MLKitCommon (~> 0.60.0) was resolved to 0.60.0, which depends on
            GoogleDataTransport (~> 3.2)

**Comment by brianmtully** [comment]
reopened, working on it

**Comment by brianmtully** [comment]
I updated the dependencies to use the latest GoogleMLKit releases, but MLKitCommon required GoogleDataTransport 8.X while the latest FlutterFire requires GoogleDataTransport 9.X. I'm not sure what I can do, I believe MLKitCommon needs to update their dependency.

**Comment by brianmtully** [comment]
https://github.com/googlesamples/mlkit/issues/300

This issue was opened yesterday. Following it for updates

**Comment by awsdataarchitect** [comment]
> https://github.com/googlesamples/mlkit/issues/300
> 
> 
> 
> This issue was opened yesterday. Following it for updates

Is this fixed in 0.0.5?

**Comment by brianmtully** [comment]
No, google has not updated the mlkit packages to fix the issue. There is nothing I can do until they update their dependency in the mlkit packages.

**Comment by awsdataarchitect** [comment]
Anyone has luck with google_ml_kit ? I read somewhere that this one works with the google transport dependency

**Comment by brianmtully** [comment]
? This library works. This issue is with regards to using google MLKit with the newest version of firebase (version 8). If you arent using flutter firebase in your project, or are using version 7 it will work.

**Comment by lvlrSajjad** [comment]
```
[!] CocoaPods could not find compatible versions for pod "GoogleDataTransport":
  In Podfile:
    firebase_performance (from `.symlinks/plugins/firebase_performance/ios`) was resolved to 0.7.0-3, which depends on
      Firebase/Performance (= 8.0.0) was resolved to 8.0.0, which depends on
        FirebasePerformance (~> 8.0.0) was resolved to 8.0.0, which depends on
          GoogleDataTransport (~> 9.0)

    google_ml_vision (from `.symlinks/plugins/google_ml_vision/ios`) was resolved to 0.0.5, which depends on
      GoogleMLKit/ImageLabeling (~> 2.1.0) was resolved to 2.1.0, which depends on
        GoogleMLKit/MLKitCore (= 2.1.0) was resolved to 2.1.0, which depends on
          MLKitCommon (~> 2.1.0) was resolved to 2.1.0, which depends on
            GoogleDataTransport (~> 8.0)
```
The issue still exists with the latest firebase versions.

**Comment by lvlrSajjad** [comment]
@brianmtully Which versions of these plugins may work with this plugin? (I may consider downgrading my firebase plugins)
```
  cloud_firestore: ^2.2.0
  cloud_functions: ^1.1.0
  firebase_analytics: ^8.1.0
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  firebase_crashlytics: ^2.0.4
  firebase_messaging: ^10.0.0
  firebase_performance: ^0.7.0+3
  firebase_remote_config: ^0.10.0
  firebase_storage: ^8.1.0
```

**Comment by awsdataarchitect** [comment]
I added this line in pod file and it looks like pod is getting downloaded now   pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '8.0.0'

**Comment by swissonid** [comment]
@brianmtully it looks like the Bug is closed https://issuetracker.google.com/issues/188452839#comment13

**Comment by brianmtully** [comment]
working on updating now

**Comment by brianmtully** [comment]
0.0.6 has been published with the updated dependencies. Closing issue.
