### ISSUE TITLE
Returning detected Text from Image

### ISSUE THREAD

**Issue by Patrick-Vogt** [brianmtully/flutter_google_ml_vision#21]
Hello, 

I am using the latest version and I have a quick & dirty function to take a photo and to read the text from that photo. 

```
onPressed: () async {
                        final picker = ImagePicker();

                        final pickedFile = await picker.getImage(
                          source: ImageSource.camera,
                        );

                        var finalImageFile = File(pickedFile!.path);
                        logger.d(finalImageFile);
                        final GoogleVisionImage visionImage =
                            GoogleVisionImage.fromFile(finalImageFile);

                        final TextRecognizer textRecognizer =
                            GoogleVision.instance.textRecognizer();
                        final VisionText visionText =
                            await textRecognizer.processImage(visionImage);

                        String? text = visionText.text;
                        logger.d(text);

                        for (TextBlock block in visionText.blocks) {
                          final Rect boundingBox = block.boundingBox!;
                          final List<Offset> cornerPoints = block.cornerPoints;
                          final String? text = block.text;
                          final List<RecognizedLanguage> languages =
                              block.recognizedLanguages;

                          for (TextLine line in block.lines) {
                            // Same getters as TextBlock
                            for (TextElement element in line.elements) {
                              logger.d(element.text!);
                              logger.d('element');
                            }
                          }
                        }
                        logger.d('endloop');
                        logger.d(text!);
                        textRecognizer.close();
                      },
```

I am using a Logger Package, to debug on a physical device. 

At first, following error appears immediately after opening the camera (So it's not related to this package)

[Camera] Failed to read exposureBiasesByMode dictionary: Error Domain=NSCocoaErrorDomain Code=4864 "*** -[NSKeyedUnarchiver _initForReadingFromData:error:throwLegacyExceptions:]: data is NULL" UserInfo={NSDebugDescription=*** -[NSKeyedUnarchiver _initForReadingFromData:error:throwLegacyExceptions:]: data is NULL}

After taking a photo it returns the path correctly. 

But, how do I return all the detected text? This is not clear to me. Even though I have several log function in the foor loop for example, it doesn't return any text. 

Is there something I'm doing wrong? I just need the recognised text, without any color, preview etc. 

Thank you for any kind of help - it's really appreciated!  :)

**Comment by brianmtully** [comment]
There is nothing that looks incorrect in your code. Maybe play with the image quality? What is the device/os version are you running?

**Comment by Patrick-Vogt** [comment]
Thanks for your quick response. 
I figured it out and it works now. 

But:
It returns nothing, if the phone is held in portrait mode - only landscape mode (with home button to the right) seems to work.
I will do some more research - Thank you for your help :)
