### ISSUE TITLE
declaration of 'MLKTextRecognizedLanguage' must be imported from module 'MLKitTextRecognitionCommon.MLKTextRecognizedLanguage' before it is required

### ISSUE THREAD

**Issue by flutterTamauze** [brianmtully/flutter_google_ml_vision#30]
I have this error when i updated my xcode anyone can help ?

**Comment by musthafa1996** [comment]
Hi everyone. The following PR fixes this issue: https://github.com/brianmtully/flutter_google_ml_vision/pull/37.

**Comment by lvlrSajjad** [comment]
I am still having this issue with the latest version 0.0.8 and latest flutter version.
