### ISSUE TITLE
Thank you for this!

### ISSUE THREAD

**Issue by acoutts** [brianmtully/flutter_google_ml_vision#7]
The official `firebase_ml_vision` package has been dead/unmaintained for months now. This was a very easy switch-out and everything seems to work as before.

Thank you for creating this!

**Comment by hmarat** [comment]
@acoutts It does not work for me. Can you help me to configure it?

**Comment by nirbar89** [comment]
> @acoutts It does not work for me. Can you help me to configure it?

Sure, where is the issue?

**Comment by festapp86** [comment]
The plugin works fine for Android. But if we want to flutter run the ios project we are receiving this error for the file FLTGoogleMlVisionPlugin.h:

`    ...Debug-iphoneos/google_ml_vision/google_ml_vision.framework/Headers/FLTGoogleMlVisionPlugin.h:7:1: error: use of '@import' when C++ modules are disabled, consider using -fmodules and -fcxx-modules
    @import MLKitVision;
    ^
    .../Debug-iphoneos/google_ml_vision/google_ml_vision.framework/Headers/FLTGoogleMlVisionPlugin.h:16:26: error: expected a type
    - (void)handleDetection:(MLKVisionImage *)image result:(FlutterResult)result;`

We have enabled modules C and Objective-C in our Target Build Settings, but it is still not working
![image](https://user-images.githubusercontent.com/36590923/119223416-9dae4900-baf9-11eb-8da8-13908b934137.png)

**Comment by festapp86** [comment]
It seems like I was able to fix it by replacing
`@import MKKitVision`
with
`#import <MLKitVision/MLKitVision.h>`
